% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  12pt]{article}
\usepackage{xcolor}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\usepackage{longtable,booktabs,array}
\newcounter{none} % for unnumbered tables
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother





\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 
\usepackage[]{natbib}
\bibliographystyle{agsm}


\addtolength{\oddsidemargin}{-.5in}%
\addtolength{\evensidemargin}{-1in}%
\addtolength{\textwidth}{1in}%
\addtolength{\textheight}{1.7in}%
\addtolength{\topmargin}{-1in}%
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Introduction},
  pdfauthor={Stacy Bowler; Derrik Miller},
  pdfkeywords={Regression, Used Vehicles, Predictive Analytics, Vehicle
Valuation},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}



\begin{document}


\def\spacingset#1{\renewcommand{\baselinestretch}%
{#1}\small\normalsize} \spacingset{1}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\date{June 19, 2026}
\title{\bf Introduction}
\author{
Stacy Bowler\\
Utah State University\\
and\\Derrik Miller\\
Utah State University\\
}
\maketitle

\bigskip
\bigskip
\begin{abstract}
This project develops a multiple linear regression model to estimate
used vehicle selling prices from vehicle characteristics, condition,
mileage, model, and geographic location. The resulting model explains
approximately 82\% of the variation in observed selling prices and
provides a framework for supporting vehicle acquisition, pricing, and
inventory decisions.
\end{abstract}

\noindent%
{\it Keywords:} Regression, Used Vehicles, Predictive Analytics, Vehicle
Valuation
\vfill

\newpage
\spacingset{1.9} % DON'T change the spacing!


The objective of this project is to develop a predictive model capable
of estimating the market value of used vehicles. Accurate vehicle
valuation supports pricing decisions for dealerships, fleet operators,
auction participants, and vehicle purchasing organizations.

The business decision addressed by this analysis is:

\begin{quote}
Given a used vehicle's characteristics, what selling price should be
expected in the current market?
\end{quote}

The resulting model can be used to identify vehicles that appear
underpriced or overpriced relative to market expectations.

\section{Business Objective}\label{business-objective}

The primary objective is to minimize pricing error between predicted and
observed vehicle sale prices.

A practical loss function for this problem is Mean Squared Error (MSE):

\[
MSE=\frac{1}{n}\sum_{i=1}^{n}(y_i-\hat{y_i})^2
\]

where:

\begin{itemize}
\tightlist
\item
  \(y_i\) is the observed selling price
\item
  \(\hat{y_i}\) is the predicted selling price
\end{itemize}

Lower prediction error improves decision quality by reducing the
likelihood of overpaying for inventory or undervaluing vehicles during
resale.

\section{Plan}\label{sec-plan}

The analysis follows the regression modeling workflow:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Define the business problem.
\item
  Acquire and clean vehicle sales data.
\item
  Explore relationships between candidate predictors and selling price.
\item
  Build an interpretable regression model.
\item
  Evaluate assumptions and model fit.
\item
  Generate predictions and business recommendations.
\end{enumerate}

The ideal dataset would contain:

\begin{itemize}
\tightlist
\item
  Vehicle age
\item
  Odometer reading
\item
  Mechanical condition
\item
  Original MSRP
\item
  Vehicle trim level
\item
  Accident history
\item
  Maintenance history
\item
  Regional market conditions
\item
  Vehicle Make/Model
\item
  Sell price
\end{itemize}

Several of these variables were unavailable. Vehicle model and state
were therefore used as proxy variables for differences in vehicle
desirability and regional pricing effects.

\section{Build}\label{sec-build}

\subsection{Data Source}\label{data-source}

The dataset was obtained from the Kaggle used vehicle auction dataset
used throughout this project.

Variables initially available included:

\begin{itemize}
\tightlist
\item
  Year
\item
  Make
\item
  Model
\item
  Transmission
\item
  State
\item
  Condition
\item
  Odometer
\item
  Selling price
\end{itemize}

\subsection{Data Cleaning}\label{data-cleaning}

The following preprocessing steps were performed:

\begin{itemize}
\tightlist
\item
  Removed records with missing values in critical fields.
\item
  Calculated vehicle age from model year.
\item
  Converted odometer values into units of 10,000 miles.
\item
  Standardized categorical values.
\item
  Grouped low-frequency vehicle models into manufacturer-specific
  ``Other'' categories.
\item
  Grouped low-frequency states into broader state categories.
\item
  Created dummy variables for categorical predictors.
\end{itemize}

\subsection{Sampling Strategy}\label{sampling-strategy}

A stratified sampling approach was used to preserve state representation
while reducing dataset size to 5000 for modeling.

Training and testing partitions were generated after sampling to
maintain representative geographic distributions.

\section{Explore}\label{sec-explore}

\subsection{Exploratory Data Analysis}\label{exploratory-data-analysis}

Initial visualizations focused on the relationships between selling
price and major numerical predictors.

\pandocbounded{\includegraphics[keepaspectratio]{Report_files/figure-pdf/cell-3-output-1.pdf}}

\begin{itemize}
\tightlist
\item
  A log transformation was applied to the selling price.
\end{itemize}

\subsection{Vehicle Age vs Selling
Price}\label{vehicle-age-vs-selling-price}

Vehicle age showed a strong negative relationship with price. Older
vehicles generally sold for substantially less than newer vehicles.

\pandocbounded{\includegraphics[keepaspectratio]{Report_files/figure-pdf/cell-4-output-1.pdf}}

\subsection{Odometer vs Selling Price}\label{odometer-vs-selling-price}

Vehicles with higher mileage generally sold for lower prices. The
relationship was weaker than vehicle age but remained statistically
significant.

\pandocbounded{\includegraphics[keepaspectratio]{Report_files/figure-pdf/cell-5-output-1.pdf}}

\subsection{Key Findings}\label{key-findings}

\begin{itemize}
\tightlist
\item
  Vehicle age exhibits the strongest continuous predictor effect.
\item
  Mileage has a meaningful negative effect on vehicle value.
\item
  Vehicle model accounts for substantial differences in selling price.
\item
  Trucks and heavy-duty pickups tend to command premium prices.
\item
  Geographic location contributes measurable price variation.
\end{itemize}

\section{Reconcile}\label{sec-reconcile}

\subsection{Assumptions}\label{assumptions}

Multiple linear regression requires:

\begin{itemize}
\tightlist
\item
  Linear relationships
\item
  Independent observations
\item
  Constant variance
\item
  Approximately normal residuals
\item
  Limited multicollinearity
\end{itemize}

\subsection{Model Refinements}\label{model-refinements}

Several iterations of the model were evaluated.

Adjustments included:

\begin{itemize}
\tightlist
\item
  Consolidating sparse model categories.
\item
  Grouping low-frequency states.
\item
  Transforming odometer readings to improve interpretability.
\item
  Evaluating Variance Inflation Factors (VIFs).
\end{itemize}

These modifications reduced model complexity while preserving predictive
performance.

\begin{verbatim}
                  Variable         VIF
0                    const  178.803946
102       state_grouped_fl    6.907212
100       state_grouped_ca    6.474079
63   model_chevrolet_Other    6.085027
9             model_Altima    4.928018
..                     ...         ...
67        model_fiat_Other    1.193466
90        model_saab_Other    1.107573
93       model_smart_Other    1.103110
74       model_isuzu_Other    1.082286
65      model_daewoo_Other    1.040533

[124 rows x 2 columns]
\end{verbatim}

Our original VIF showed high values with mmr, make, and body. Mmr is a
market estimate for the worth of the vehicle so it made sense that
predictor overpowered all of the other predictors. Likewise, it's a
pretty safe assumption that the vehicle model was already capturing the
make and body. For example a vehicle model of `Ram 1500' only refers to
a dodge truck so the model can easily deduce that data from the vehicle
model so including those in the model was redundant.

Our current model shows no VIF values above or close to 10 so there
appear to be no concerns there.

\begin{verbatim}
Text(0.5, 1.0, 'Residuals vs Fitted')
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{Report_files/figure-pdf/cell-7-output-2.pdf}}

This graph shows a decent cloud not indicating any concerns.

\begin{verbatim}
Text(0.5, 1.0, 'Q-Q Plot')
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{Report_files/figure-pdf/cell-8-output-2.pdf}}

Our QQ plot is not great, but we already applied a log transform so
there's not much more that can be done. This QQ plot shape is not
uncommon with sales data and some of the shape may be accounted for that
we have vehicle model and state predictors that are categorical rather
than linear and are a significant part of the model.

\section{Fit}\label{sec-fit}

\subsection{Final Model}\label{final-model}

The final model included:

\begin{itemize}
\tightlist
\item
  Vehicle age
\item
  Odometer (10,000-mile units)
\item
  Condition score
\item
  Vehicle model
\item
  State group
\end{itemize}

\begin{verbatim}
                            OLS Regression Results                            
==============================================================================
Dep. Variable:           sellingprice   R-squared:                       0.818
Model:                            OLS   Adj. R-squared:                  0.812
Method:                 Least Squares   F-statistic:                     141.6
Date:                Fri, 19 Jun 2026   Prob (F-statistic):               0.00
Time:                        22:24:48   Log-Likelihood:                -1715.4
No. Observations:                4000   AIC:                             3679.
Df Residuals:                    3876   BIC:                             4459.
Df Model:                         123                                         
Covariance Type:            nonrobust                                         
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
const                        10.0407      0.080    125.821      0.000       9.884      10.197
vehicle_age                  -0.1279      0.003    -44.877      0.000      -0.134      -0.122
odometer_10k                 -0.0508      0.002    -24.010      0.000      -0.055      -0.047
condition                     0.0073      0.001     14.577      0.000       0.006       0.008
model_200                    -0.6800      0.097     -6.995      0.000      -0.871      -0.489
model_3 Series                0.0911      0.082      1.113      0.266      -0.069       0.252
model_300                    -0.0872      0.100     -0.876      0.381      -0.282       0.108
model_5 Series                0.3066      0.099      3.104      0.002       0.113       0.500
model_Accord                 -0.2591      0.082     -3.175      0.002      -0.419      -0.099
model_Altima                 -0.4687      0.075     -6.227      0.000      -0.616      -0.321
model_Avenger                -0.7208      0.091     -7.921      0.000      -0.899      -0.542
model_C-Class                 0.0999      0.090      1.116      0.264      -0.076       0.275
model_CR-V                    0.1006      0.107      0.941      0.347      -0.109       0.310
model_Camry                  -0.3019      0.078     -3.865      0.000      -0.455      -0.149
model_Charger                -0.0663      0.098     -0.673      0.501      -0.259       0.127
model_Civic                  -0.4153      0.086     -4.853      0.000      -0.583      -0.248
model_Corolla                -0.4822      0.084     -5.756      0.000      -0.646      -0.318
model_Cruze                  -0.6591      0.090     -7.338      0.000      -0.835      -0.483
model_E-Class                 0.3532      0.096      3.673      0.000       0.165       0.542
model_Edge                   -0.0024      0.090     -0.027      0.978      -0.179       0.174
model_Elantra                -0.6615      0.086     -7.688      0.000      -0.830      -0.493
model_Equinox                -0.2747      0.087     -3.153      0.002      -0.446      -0.104
model_Escape                 -0.2795      0.077     -3.647      0.000      -0.430      -0.129
model_Expedition              0.1691      0.109      1.558      0.119      -0.044       0.382
model_Explorer                0.0166      0.085      0.195      0.845      -0.150       0.184
model_F-150                   0.2495      0.078      3.181      0.001       0.096       0.403
model_F-250 Super Duty        0.5993      0.100      5.968      0.000       0.402       0.796
model_Focus                  -0.7664      0.078     -9.873      0.000      -0.919      -0.614
model_Fusion                 -0.4933      0.077     -6.412      0.000      -0.644      -0.342
model_G Sedan                -0.0277      0.084     -0.331      0.740      -0.192       0.136
model_Grand Caravan          -0.3861      0.086     -4.490      0.000      -0.555      -0.218
model_Grand Cherokee          0.0804      0.097      0.832      0.406      -0.109       0.270
model_Impala                 -0.5320      0.084     -6.326      0.000      -0.697      -0.367
model_Jetta                  -0.5260      0.100     -5.246      0.000      -0.723      -0.329
model_Journey                -0.3347      0.095     -3.531      0.000      -0.521      -0.149
model_Liberty                -0.1972      0.109     -1.817      0.069      -0.410       0.016
model_Malibu                 -0.5346      0.085     -6.321      0.000      -0.700      -0.369
model_Maxima                 -0.2231      0.087     -2.569      0.010      -0.393      -0.053
model_Mazda3                 -0.5291      0.099     -5.332      0.000      -0.724      -0.335
model_Mustang                -0.2246      0.103     -2.187      0.029      -0.426      -0.023
model_Odyssey                -0.0549      0.098     -0.562      0.574      -0.247       0.137
model_Optima                 -0.4698      0.094     -4.988      0.000      -0.654      -0.285
model_Passat                 -0.6219      0.094     -6.632      0.000      -0.806      -0.438
model_RAV4                   -0.0871      0.104     -0.836      0.403      -0.291       0.117
model_Rogue                  -0.3026      0.096     -3.151      0.002      -0.491      -0.114
model_Sentra                 -0.6501      0.090     -7.223      0.000      -0.827      -0.474
model_Sienna                  0.1062      0.107      0.991      0.322      -0.104       0.316
model_Silverado 1500          0.2541      0.087      2.932      0.003       0.084       0.424
model_Sonata                 -0.5277      0.088     -6.028      0.000      -0.699      -0.356
model_Sorento                -0.3940      0.103     -3.843      0.000      -0.595      -0.193
model_Soul                   -0.6376      0.105     -6.050      0.000      -0.844      -0.431
model_Suburban                0.4482      0.104      4.309      0.000       0.244       0.652
model_Tahoe                   0.5444      0.100      5.462      0.000       0.349       0.740
model_Taurus                 -0.6687      0.105     -6.360      0.000      -0.875      -0.463
model_Town and Country       -0.3667      0.093     -3.946      0.000      -0.549      -0.184
model_Versa                  -0.7535      0.108     -6.969      0.000      -0.965      -0.542
model_Wrangler                0.4013      0.092      4.343      0.000       0.220       0.583
model_X5                      0.4439      0.108      4.094      0.000       0.231       0.657
model_acura_Other             0.1363      0.089      1.535      0.125      -0.038       0.310
model_audi_Other              0.2036      0.088      2.318      0.021       0.031       0.376
model_bmw_Other               0.3983      0.087      4.569      0.000       0.227       0.569
model_buick_Other            -0.3924      0.093     -4.213      0.000      -0.575      -0.210
model_cadillac_Other         -0.0152      0.081     -0.186      0.852      -0.175       0.145
model_chevrolet_Other        -0.2908      0.073     -3.962      0.000      -0.435      -0.147
model_chrysler_Other         -1.1530      0.099    -11.659      0.000      -1.347      -0.959
model_daewoo_Other           -2.2839      0.385     -5.931      0.000      -3.039      -1.529
model_dodge_Other            -0.1590      0.080     -1.997      0.046      -0.315      -0.003
model_fiat_Other             -0.9297      0.168     -5.519      0.000      -1.260      -0.599
model_ford_Other             -0.2788      0.078     -3.562      0.000      -0.432      -0.125
model_gmc_Other               0.2408      0.083      2.918      0.004       0.079       0.403
model_honda_Other            -0.0278      0.097     -0.287      0.774      -0.217       0.162
model_hummer_Other            0.8827      0.144      6.140      0.000       0.601       1.164
model_hyundai_Other          -0.4713      0.084     -5.607      0.000      -0.636      -0.306
model_infiniti_Other          0.2024      0.084      2.407      0.016       0.038       0.367
model_isuzu_Other            -0.9221      0.278     -3.320      0.001      -1.467      -0.378
model_jaguar_Other            0.2494      0.129      1.935      0.053      -0.003       0.502
model_jeep_Other             -0.3907      0.090     -4.343      0.000      -0.567      -0.214
model_kia_Other              -0.7087      0.083     -8.545      0.000      -0.871      -0.546
model_land rover_Other        0.6535      0.129      5.075      0.000       0.401       0.906
model_lexus_Other             0.3985      0.080      4.990      0.000       0.242       0.555
model_lincoln_Other          -0.1519      0.093     -1.631      0.103      -0.334       0.031
model_mazda_Other            -0.5526      0.089     -6.230      0.000      -0.727      -0.379
model_mercedes-benz_Other     0.5828      0.088      6.641      0.000       0.411       0.755
model_mercury_Other          -0.4185      0.138     -3.042      0.002      -0.688      -0.149
model_mini_Other             -0.3755      0.107     -3.515      0.000      -0.585      -0.166
model_mitsubishi_Other       -0.6594      0.094     -6.988      0.000      -0.844      -0.474
model_nissan_Other           -0.1042      0.078     -1.333      0.183      -0.258       0.049
model_pontiac_Other          -0.7952      0.097     -8.183      0.000      -0.986      -0.605
model_porsche_Other           1.0412      0.150      6.931      0.000       0.747       1.336
model_ram_Other               0.3523      0.158      2.224      0.026       0.042       0.663
model_saab_Other             -0.7784      0.229     -3.393      0.001      -1.228      -0.329
model_saturn_Other           -0.7523      0.101     -7.435      0.000      -0.951      -0.554
model_scion_Other            -0.5546      0.150     -3.701      0.000      -0.848      -0.261
model_smart_Other            -1.1332      0.229     -4.949      0.000      -1.582      -0.684
model_subaru_Other           -0.1688      0.096     -1.750      0.080      -0.358       0.020
model_suzuki_Other           -0.6913      0.138     -5.004      0.000      -0.962      -0.420
model_toyota_Other            0.1528      0.077      1.994      0.046       0.003       0.303
model_volkswagen_Other       -0.2980      0.093     -3.221      0.001      -0.479      -0.117
model_volvo_Other            -0.2249      0.098     -2.284      0.022      -0.418      -0.032
state_grouped_az              0.0218      0.062      0.349      0.727      -0.100       0.144
state_grouped_ca              0.1581      0.044      3.599      0.000       0.072       0.244
state_grouped_co              0.0942      0.067      1.399      0.162      -0.038       0.226
state_grouped_fl              0.1232      0.043      2.842      0.005       0.038       0.208
state_grouped_ga              0.1410      0.047      3.004      0.003       0.049       0.233
state_grouped_il              0.1443      0.050      2.909      0.004       0.047       0.242
state_grouped_in              0.0447      0.078      0.574      0.566      -0.108       0.197
state_grouped_ma             -0.0426      0.066     -0.648      0.517      -0.171       0.086
state_grouped_md             -0.0296      0.059     -0.503      0.615      -0.145       0.086
state_grouped_mi              0.1618      0.054      3.024      0.003       0.057       0.267
state_grouped_mn              0.2002      0.060      3.332      0.001       0.082       0.318
state_grouped_mo              0.1418      0.053      2.678      0.007       0.038       0.246
state_grouped_nc              0.1157      0.051      2.268      0.023       0.016       0.216
state_grouped_ne              0.1334      0.080      1.676      0.094      -0.023       0.290
state_grouped_nj              0.0773      0.049      1.565      0.118      -0.020       0.174
state_grouped_nv              0.1024      0.056      1.836      0.066      -0.007       0.212
state_grouped_ny              0.0479      0.072      0.661      0.508      -0.094       0.190
state_grouped_oh              0.0613      0.050      1.225      0.221      -0.037       0.159
state_grouped_pa              0.1496      0.049      3.054      0.002       0.054       0.246
state_grouped_sc              0.1564      0.076      2.059      0.040       0.007       0.305
state_grouped_tn              0.1271      0.050      2.528      0.011       0.029       0.226
state_grouped_tx              0.0745      0.045      1.646      0.100      -0.014       0.163
state_grouped_va              0.0361      0.059      0.617      0.537      -0.079       0.151
state_grouped_wa              0.0933      0.064      1.462      0.144      -0.032       0.218
state_grouped_wi              0.1179      0.059      1.989      0.047       0.002       0.234
==============================================================================
Omnibus:                      499.223   Durbin-Watson:                   2.020
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3013.924
Skew:                          -0.431   Prob(JB):                         0.00
Kurtosis:                       7.164   Cond. No.                     3.85e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.85e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
\end{verbatim}

The fitted model produced:

\begin{itemize}
\tightlist
\item
  R² = 0.818
\item
  Adjusted R² = 0.812
\item
  F-statistic = 141.6
\item
  p \textless{} 0.001
\end{itemize}

indicating strong overall explanatory power.

\subsection{Important Continuous
Predictors}\label{important-continuous-predictors}

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}lr@{}}
\toprule\noalign{}
Variable & Coefficient \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Vehicle Age & -0.1279 \\
Odometer (10k miles) & -0.0508 \\
Condition & 0.0073 \\
\end{longtable}
}

Because the dependent variable is log-transformed, coefficients can be
approximately interpreted as percentage changes.

\subsubsection{Vehicle Age}\label{vehicle-age}

Each additional year reduces expected selling price by approximately:

\[
100(e^{-0.1279}-1) \approx -12.0\%
\]

\subsubsection{Odometer}\label{odometer}

Each additional 10,000 miles reduces expected selling price by
approximately:

\[
100(e^{-0.0508}-1) \approx -5.0\%
\]

\subsubsection{Condition}\label{condition}

Each one-point increase in condition increases expected selling price by
approximately:

\[
100(e^{0.0073}-1) \approx 0.7\%
\]

\section{Evaluate}\label{sec-evaluate}

\subsection{Residual Analysis}\label{residual-analysis}

Residual diagnostics indicated:

\begin{itemize}
\tightlist
\item
  No severe violations of linearity.
\item
  Acceptable residual symmetry.
\item
  Some heavy tails remain.
\item
  No extreme multicollinearity concerns.
\end{itemize}

The largest VIF values were associated with popular truck categories but
remained below commonly cited thresholds requiring corrective action.

\subsection{Limitations}\label{limitations}

Several limitations should be noted:

\begin{itemize}
\tightlist
\item
  No MSRP information was available.
\item
  Trim level information was not incorporated.
\item
  Accident history was unavailable.
\item
  Maintenance records were unavailable.
\item
  Auction data may not represent all vehicle markets.
\end{itemize}

These limitations likely explain a portion of the unexplained variance.

\section{Predict}\label{sec-predict}

\subsection{Business Implications}\label{business-implications}

The model suggests:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Vehicle age is the strongest continuous driver of depreciation.
\item
  Mileage has a significant but smaller effect.
\item
  Vehicle model contributes substantial value differences.
\item
  Trucks generally retain value better than passenger sedans.
\end{enumerate}

\subsection{Recommendations}\label{recommendations}

Organizations purchasing used vehicles should:

\begin{itemize}
\tightlist
\item
  Prioritize lower-age vehicles when possible.
\item
  Consider mileage alongside age rather than in isolation.
\item
  Use model-specific adjustments when evaluating value.
\item
  Compare observed asking prices against model predictions to identify
  unusually favorable purchasing opportunities.
\end{itemize}

\subsection{Future Work}\label{future-work}

Future improvements could include:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Incorporating original MSRP.
\item
  Including trim-level information.
\item
  Adding accident-history variables.
\item
  Incorporating local economic indicators.
\end{enumerate}

\section{Conclusion}\label{conclusion}

The final regression model explains approximately 82\% of the variation
in used vehicle selling prices and provides a practical framework for
vehicle valuation. Vehicle age, mileage, model, and geographic location
all contribute significantly to price determination. The resulting model
can support data-driven purchasing and pricing decisions while
highlighting areas for future model enhancement.


\bibliography{references.bib}



\end{document}
